
source 'https://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'

# site_prim é um framework que foi feito pra implementar pageobject inspecialmente pro capybara